<a href="https://colab.research.google.com/github/raphaelp-silva/deep_learning_com_pytorch_e_python/blob/main/Projeto_5_Classifica%C3%A7%C3%A3o_bin%C3%A1ria_breast_cancer_carregar_o_classificador.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto 5: Classificação binária brest cancer - carregar o classificador

## Etapa 1: Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import accuracy_score
torch.__version__

'2.5.1+cu124'

## Etapa 2: Carregamento do classificador

In [2]:
np.random.seed(123)
torch.manual_seed(123)

In [3]:
class classificador_torch(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense0 = nn.Linear(30, 8)
        torch.nn.init.normal_(self.dense0.weight, mean = 0.0, std = 0.05)
        self.dense1 = nn.Linear(8, 8)
        torch.nn.init.normal_(self.dense1.weight, mean = 0.0, std = 0.05)
        self.dense2 = nn.Linear(8, 1)
        self.activation = nn.ReLU()
        self.dropout = nn.Dropout(0.2)
        self.output = nn.Sigmoid()

    def forward(self, X):
        X = self.dense0(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense1(X)
        X = self.activation(X)
        X = self.dropout(X)
        X = self.dense2(X)
        X = self.output(X)
        return X

In [4]:
classificador = classificador_torch()

In [5]:
# carregando o arquivo salvo no exercicio anterior
state_dict = torch.load('/content/checkpoint.pth')

<ipython-input-5-76b916dc1e55>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load('/content/checkpoint.pth')


In [6]:
state_dict

OrderedDict([('dense0.weight',
              tensor([[-6.3329e-01, -6.4088e-03, -3.8681e-01, -1.0687e-01,  9.4179e-02,
                       -2.8071e-02,  5.8217e-02, -5.5828e-02,  1.4919e-02,  5.5338e-02,
                        8.5171e-03, -1.0727e-03,  3.1089e-03, -1.7085e-02,  3.1640e-02,
                        2.3500e-01, -3.9340e-01, -1.7852e-01, -6.7033e-02,  5.4838e-01,
                       -4.7472e-01,  2.4388e-02, -3.2421e-01,  1.8188e-01,  1.4345e-02,
                        3.0411e-02,  1.2222e-02,  4.2423e-02,  1.6629e-02,  6.2451e-01],
                      [ 9.6147e-02,  8.9823e-03,  6.2657e-02, -2.7833e-02,  2.5520e-02,
                       -1.4683e-02,  8.4852e-09, -5.5642e-02, -4.3206e-02,  2.9459e-04,
                        3.3087e-02,  1.5457e-03, -3.6564e-02,  7.3219e-02, -9.4868e-11,
                       -5.2539e-07,  3.7381e-03,  2.0600e-09,  6.6002e-09,  2.5737e-10,
                       -7.0341e-02,  3.3297e-02, -3.6295e-02, -3.3981e-02, -7.6689e-02,


In [8]:
# carregando os pesos:
classificador.load_state_dict(state_dict)

<All keys matched successfully>

## Etapa 3: Previsões


In [9]:
novo = torch.tensor([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                      0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                      0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                      0.84, 158, 0.363]])

In [10]:
classificador.eval()
previsao = classificador(novo)
previsao = (previsao.detach().numpy() > 0.5)
previsao

array([[ True]])

In [12]:
# carregando base de dados para ser avaliadas pelo modelo que já foi treinado:
previsores = pd.read_csv('entradas_breast.csv')
classe = pd.read_csv('saidas_breast.csv')

In [13]:
# convertendo o arquivo para array numpy:
previsores = torch.tensor(np.array(previsores), dtype = torch.float)
classe = torch.tensor(np.array(classe), dtype = torch.float)

In [14]:
previsoes = classificador.forward(previsores).detach()

In [15]:
previsoes

tensor([[5.2292e-07],
        [9.2073e-05],
        [1.0848e-03],
        [1.5193e-04],
        [1.2827e-02],
        [5.7314e-01],
        [7.7519e-05],
        [2.3465e-01],
        [3.0953e-01],
        [6.9902e-03],
        [1.2647e-01],
        [4.5155e-03],
        [2.5287e-01],
        [6.8647e-01],
        [6.8647e-01],
        [4.6997e-01],
        [3.0779e-02],
        [3.7884e-03],
        [3.9827e-08],
        [9.6103e-01],
        [6.8647e-01],
        [1.0000e+00],
        [3.9961e-01],
        [2.4730e-08],
        [1.7898e-08],
        [2.7582e-04],
        [4.2254e-01],
        [1.6693e-02],
        [1.7407e-03],
        [1.9918e-01],
        [1.4824e-03],
        [5.1415e-02],
        [1.2670e-02],
        [7.5736e-05],
        [5.3576e-03],
        [9.8634e-02],
        [6.8647e-01],
        [9.9928e-01],
        [6.8647e-01],
        [6.3165e-01],
        [6.6119e-01],
        [8.2413e-01],
        [1.3902e-04],
        [1.4843e-01],
        [6.8647e-01],
        [1

In [16]:
#tendo o retorno de erro:
F.binary_cross_entropy(previsoes, classe).numpy()

array(0.19902813, dtype=float32)

In [18]:
#visualizando a accuracy:
accuracy_score(classe.numpy(), (previsoes > 0.5).numpy())

0.9332161687170475